f---
title: "myprezdata"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
setwd("/Users/alex/Desktop/fpeds_alex")
library(tidyverse)
library(readxl)
library(ggplot2)
library(ggthemes)
library(gridExtra)

```


The following code below is used for my own reference to pull the correct timeframes from online.
```{r cars}
electionDates <- c("1980-11-4", "1984-11-6", "1988-11-8", "1992-11-3", "1996-11-5", "2000-11-7", "2004-11-2", "2008-11-4", "2012-11-6", "2016-11-8")
initData <- as.Date(electionDates) - 90 # this is the date that we will begin tracking the market (also the date that is 3 months before the election for that corresponding year). we will track for a month after the election date.
postData <- as.Date(electionDates) + 30
initData
postData
```


```{r}
par(mfrow=c(2,2))

market2000 <- read_excel("electionsp500.xlsx", sheet = "2000")
market2004 <- read_excel("electionsp500.xlsx", sheet = "2004")
market2008 <- read_excel("electionsp500.xlsx", sheet = "2008")
market2012 <- read_excel("electionsp500.xlsx", sheet = "2012")
market2016 <- read_excel("electionsp500.xlsx", sheet = "2016")


winners <- c("2000R", "2004R", "2008D", "2012D", "2016R" )

#Graphs

#graphOfReturns2000 <- ggplot(data = market2000, aes(x = date, y = return)) + geom_smooth(method=lm, color = "red")
#graphOfReturns2004 <- ggplot(data = market2004, aes(x = date, y = return)) + geom_smooth(method=lm, color = "red")
#graphOfReturns2008 <- ggplot(data = market2008, aes(x = date, y = return)) + geom_smooth(method=lm, color = "blue")
#graphOfReturns2012 <- ggplot(data = market2012, aes(x = date, y = return)) + geom_smooth(method=lm, color = "blue")
#graphOfReturns2016 <- ggplot(data = market2016, aes(x = date, y = return)) + geom_smooth(method=lm, color = "red")

#graphOfReturns2000
#graphOfReturns2004
#graphOfReturns2008
#graphOfReturns2012
#graphOfReturns2016
```
```{r}
#Data for each industry, each election
consumerGoods2000 <- read_excel("consumerGoodsReturns.xlsx", sheet = "2000")
consumerGoods2004 <- read_excel("consumerGoodsReturns.xlsx", sheet = "2004")
consumerGoods2008 <- read_excel("consumerGoodsReturns.xlsx", sheet = "2008")
consumerGoods2012 <- read_excel("consumerGoodsReturns.xlsx", sheet = "2012")
consumerGoods2016 <- read_excel("consumerGoodsReturns.xlsx", sheet = "2016")

realEstate2000 <- read_excel("realEstateReturns.xlsx", sheet = "2000")
realEstate2004 <- read_excel("realEstateReturns.xlsx", sheet = "2004")
realEstate2008 <- read_excel("realEstateReturns.xlsx", sheet = "2008")
realEstate2012 <- read_excel("realEstateReturns.xlsx", sheet = "2012")
realEstate2016 <- read_excel("realEstateReturns.xlsx", sheet = "2016")

telecommunications2000 <- read_excel("telecommunicationsReturns.xlsx", sheet = "2000")
telecommunications2004 <- read_excel("telecommunicationsReturns.xlsx", sheet = "2004")
telecommunications2008 <- read_excel("telecommunicationsReturns.xlsx", sheet = "2008")
telecommunications2012 <- read_excel("telecommunicationsReturns.xlsx", sheet = "2012")
telecommunications2016 <- read_excel("telecommunicationsReturns.xlsx", sheet = "2016")

utilities2000 <- read_excel("utilitiesReturns.xlsx", sheet = "2000")
utilities2004 <- read_excel("utilitiesReturns.xlsx", sheet = "2004")
utilities2008 <- read_excel("utilitiesReturns.xlsx", sheet = "2008")
utilities2012 <- read_excel("utilitiesReturns.xlsx", sheet = "2012")
utilities2016 <- read_excel("utilitiesReturns.xlsx", sheet = "2016")

technology2000 <- read_excel("technologyReturns.xlsx", sheet = "2000")
technology2004 <- read_excel("technologyReturns.xlsx", sheet = "2004")
technology2008 <- read_excel("technologyReturns.xlsx", sheet = "2008")
technology2012 <- read_excel("technologyReturns.xlsx", sheet = "2012")
technology2016 <- read_excel("technologyReturns.xlsx", sheet = "2016")

industrial2000 <- read_excel("industrialReturns.xlsx", sheet = "2000")
industrial2004 <- read_excel("industrialReturns.xlsx", sheet = "2004")
industrial2008 <- read_excel("industrialReturns.xlsx", sheet = "2008")
industrial2012 <- read_excel("industrialReturns.xlsx", sheet = "2012")
industrial2016 <- read_excel("industrialReturns.xlsx", sheet = "2016")

financial2000 <- read_excel("financialReturns.xlsx", sheet = "2000")
financial2004 <- read_excel("financialReturns.xlsx", sheet = "2004")
financial2008 <- read_excel("financialReturns.xlsx", sheet = "2008")
financial2012 <- read_excel("financialReturns.xlsx", sheet = "2012")
financial2016 <- read_excel("financialReturns.xlsx", sheet = "2016")

energy2000 <- read_excel("energyReturns.xlsx", sheet = "2000")
energy2004 <- read_excel("energyReturns.xlsx", sheet = "2004")
energy2008 <- read_excel("energyReturns.xlsx", sheet = "2008")
energy2012 <- read_excel("energyReturns.xlsx", sheet = "2012")
energy2016 <- read_excel("energyReturns.xlsx", sheet = "2016")

consumerDiscretionary2000 <- read_excel("consumerDiscretionaryReturns.xlsx", sheet = "2000")
consumerDiscretionary2004 <- read_excel("consumerDiscretionaryReturns.xlsx", sheet = "2004")
consumerDiscretionary2008 <- read_excel("consumerDiscretionaryReturns.xlsx", sheet = "2008")
consumerDiscretionary2012 <- read_excel("consumerDiscretionaryReturns.xlsx", sheet = "2012")
consumerDiscretionary2016 <- read_excel("consumerDiscretionaryReturns.xlsx", sheet = "2016")

healthCare2000 <- read_excel("healthCareReturns.xlsx", sheet = "2000")
healthCare2004 <- read_excel("healthCareReturns.xlsx", sheet = "2004")
healthCare2008 <- read_excel("healthCareReturns.xlsx", sheet = "2008")
healthCare2012 <- read_excel("healthCareReturns.xlsx", sheet = "2012")
healthCare2016 <- read_excel("healthCareReturns.xlsx", sheet = "2016")

materials2000 <- read_excel("materialsReturns.xlsx", sheet = "2000")
materials2004 <- read_excel("materialsReturns.xlsx", sheet = "2004")
materials2008 <- read_excel("materialsReturns.xlsx", sheet = "2008")
materials2012 <- read_excel("materialsReturns.xlsx", sheet = "2012")
materials2016 <- read_excel("materialsReturns.xlsx", sheet = "2016")
```


```{r}
# Pearson correlations for each industry, each election
correl_consumerGoods2000 <- cor.test(consumerGoods2000$return, market2000$return, method = "pearson")$estimate
correl_consumerGoods2004 <- cor.test(consumerGoods2004$return, market2004$return, method = "pearson")$estimate
correl_consumerGoods2008 <- cor.test(consumerGoods2008$return, market2008$return, method = "pearson")$estimate
correl_consumerGoods2012 <- cor.test(consumerGoods2012$return, market2012$return, method = "pearson")$estimate
correl_consumerGoods2016 <- cor.test(consumerGoods2016$return, market2016$return, method = "pearson")$estimate

correl_realEstate2000 <- cor.test(realEstate2000$return, market2000$return, method = "pearson")$estimate
correl_realEstate2004 <- cor.test(realEstate2004$return, market2004$return, method = "pearson")$estimate
correl_realEstate2008 <- cor.test(realEstate2008$return, market2008$return, method = "pearson")$estimate
correl_realEstate2012 <- cor.test(realEstate2012$return, market2012$return, method = "pearson")$estimate
correl_realEstate2016 <- cor.test(realEstate2016$return, market2016$return, method = "pearson")$estimate

correl_telecommunications2000 <- cor.test(telecommunications2000$return, market2000$return, method = "pearson")$estimate
correl_telecommunications2004 <- cor.test(telecommunications2004$return, market2004$return, method = "pearson")$estimate
correl_telecommunications2008 <- cor.test(telecommunications2008$return, market2008$return, method = "pearson")$estimate
correl_telecommunications2012 <- cor.test(telecommunications2012$return, market2012$return, method = "pearson")$estimate
correl_telecommunications2016 <- cor.test(telecommunications2016$return, market2016$return, method = "pearson")$estimate

correl_utilities2000 <- cor.test(utilities2000$return, market2000$return, method = "pearson")$estimate
correl_utilities2004 <- cor.test(utilities2004$return, market2004$return, method = "pearson")$estimate
correl_utilities2008 <- cor.test(utilities2008$return, market2008$return, method = "pearson")$estimate
correl_utilities2012 <- cor.test(utilities2012$return, market2012$return, method = "pearson")$estimate
correl_utilities2016 <- cor.test(utilities2016$return, market2016$return, method = "pearson")$estimate

correl_technology2000 <- cor.test(technology2000$return, market2000$return, method = "pearson")$estimate
correl_technology2004 <- cor.test(technology2004$return, market2004$return, method = "pearson")$estimate
correl_technology2008 <- cor.test(technology2008$return, market2008$return, method = "pearson")$estimate
correl_technology2012 <- cor.test(technology2012$return, market2012$return, method = "pearson")$estimate
correl_technology2016 <- cor.test(technology2016$return, market2016$return, method = "pearson")$estimate

correl_industrial2000 <- cor.test(industrial2000$return, market2000$return, method = "pearson")$estimate
correl_industrial2004 <- cor.test(industrial2004$return, market2004$return, method = "pearson")$estimate
correl_industrial2008 <- cor.test(industrial2008$return, market2008$return, method = "pearson")$estimate
correl_industrial2012 <- cor.test(industrial2012$return, market2012$return, method = "pearson")$estimate
correl_industrial2016 <- cor.test(industrial2016$return, market2016$return, method = "pearson")$estimate

correl_financial2000 <- cor.test(financial2000$return, market2000$return, method = "pearson")$estimate
correl_financial2004 <- cor.test(financial2004$return, market2004$return, method = "pearson")$estimate
correl_financial2008 <- cor.test(financial2008$return, market2008$return, method = "pearson")$estimate
correl_financial2012 <- cor.test(financial2012$return, market2012$return, method = "pearson")$estimate
correl_financial2016 <- cor.test(financial2016$return, market2016$return, method = "pearson")$estimate

correl_energy2000 <- cor.test(energy2000$return, market2000$return, method = "pearson")$estimate
correl_energy2004 <- cor.test(energy2004$return, market2004$return, method = "pearson")$estimate
correl_energy2008 <- cor.test(energy2008$return, market2008$return, method = "pearson")$estimate
correl_energy2012 <- cor.test(energy2012$return, market2012$return, method = "pearson")$estimate
correl_energy2016 <- cor.test(energy2016$return, market2016$return, method = "pearson")$estimate

correl_consumerDiscretionary2000 <- cor.test(consumerDiscretionary2000$return, market2000$return, method = "pearson")$estimate
correl_consumerDiscretionary2004 <- cor.test(consumerDiscretionary2004$return, market2004$return, method = "pearson")$estimate
correl_consumerDiscretionary2008 <- cor.test(consumerDiscretionary2008$return, market2008$return, method = "pearson")$estimate
correl_consumerDiscretionary2012 <- cor.test(consumerDiscretionary2012$return, market2012$return, method = "pearson")$estimate
correl_consumerDiscretionary2016 <- cor.test(consumerDiscretionary2016$return, market2016$return, method = "pearson")$estimate

correl_healthCare2000 <- cor.test(healthCare2000$return, market2000$return, method = "pearson")$estimate
correl_healthCare2004 <- cor.test(healthCare2004$return, market2004$return, method = "pearson")$estimate
correl_healthCare2008 <- cor.test(healthCare2008$return, market2008$return, method = "pearson")$estimate
correl_healthCare2012 <- cor.test(healthCare2012$return, market2012$return, method = "pearson")$estimate
correl_healthCare2016 <- cor.test(healthCare2016$return, market2016$return, method = "pearson")$estimate

correl_materials2000 <- cor.test(materials2000$return, market2000$return, method = "pearson")$estimate
correl_materials2004 <- cor.test(materials2004$return, market2004$return, method = "pearson")$estimate
correl_materials2008 <- cor.test(materials2008$return, market2008$return, method = "pearson")$estimate
correl_materials2012 <- cor.test(materials2012$return, market2012$return, method = "pearson")$estimate
correl_materials2016 <- cor.test(materials2016$return, market2016$return, method = "pearson")$estimate

# Standard deviation for each industry, each election

sd_consumerGoods2000 <- sd(consumerGoods2000$return)
sd_consumerGoods2004 <- sd(consumerGoods2004$return)
sd_consumerGoods2008 <- sd(consumerGoods2008$return)
sd_consumerGoods2012 <- sd(consumerGoods2012$return)
sd_consumerGoods2016 <- sd(consumerGoods2016$return)

sd_realEstate2000 <- sd(realEstate2000$return)
sd_realEstate2004 <- sd(realEstate2004$return)
sd_realEstate2008 <- sd(realEstate2008$return)
sd_realEstate2012 <- sd(realEstate2012$return)
sd_realEstate2016 <- sd(realEstate2016$return)

sd_telecommunications2000 <- sd(telecommunications2000$return)
sd_telecommunications2004 <- sd(telecommunications2004$return)
sd_telecommunications2008 <- sd(telecommunications2008$return)
sd_telecommunications2012 <- sd(telecommunications2012$return)
sd_telecommunications2016 <- sd(telecommunications2016$return)

sd_utilities2000 <- sd(utilities2000$return)
sd_utilities2004 <- sd(utilities2004$return)
sd_utilities2008 <- sd(utilities2008$return)
sd_utilities2012 <- sd(utilities2012$return)
sd_utilities2016 <- sd(utilities2016$return)

sd_technology2000 <- sd(technology2000$return)
sd_technology2004 <- sd(technology2004$return)
sd_technology2008 <- sd(technology2008$return)
sd_technology2012 <- sd(technology2012$return)
sd_technology2016 <- sd(technology2016$return)

sd_industrial2000 <- sd(industrial2000$return)
sd_industrial2004 <- sd(industrial2004$return)
sd_industrial2008 <- sd(industrial2008$return)
sd_industrial2012 <- sd(industrial2012$return)
sd_industrial2016 <- sd(industrial2016$return)

sd_financial2000 <- sd(financial2000$return)
sd_financial2004 <- sd(financial2004$return)
sd_financial2008 <- sd(financial2008$return)
sd_financial2012 <- sd(financial2012$return)
sd_financial2016 <- sd(financial2016$return)

sd_energy2000 <- sd(energy2000$return)
sd_energy2004 <- sd(energy2004$return)
sd_energy2008 <- sd(energy2008$return)
sd_energy2012 <- sd(energy2012$return)
sd_energy2016 <- sd(energy2016$return)

sd_consumerDiscretionary2000 <- sd(consumerDiscretionary2000$return)
sd_consumerDiscretionary2004 <- sd(consumerDiscretionary2004$return)
sd_consumerDiscretionary2008 <- sd(consumerDiscretionary2008$return)
sd_consumerDiscretionary2012 <- sd(consumerDiscretionary2012$return)
sd_consumerDiscretionary2016 <- sd(consumerDiscretionary2016$return)

sd_healthCare2000 <- sd(healthCare2000$return)
sd_healthCare2004 <- sd(healthCare2004$return)
sd_healthCare2008 <- sd(healthCare2008$return)
sd_healthCare2012 <- sd(healthCare2012$return)
sd_healthCare2016 <- sd(healthCare2016$return)

sd_materials2000 <- sd(materials2000$return)
sd_materials2004 <- sd(materials2004$return)
sd_materials2008 <- sd(materials2008$return)
sd_materials2012 <- sd(materials2012$return)
sd_materials2016 <- sd(materials2016$return)

# Standard deviation of overall market, each election

sd_market2000 <- sd(market2000$return)
sd_market2004 <- sd(market2004$return)
sd_market2008 <- sd(market2008$return)
sd_market2012 <- sd(market2012$return)
sd_market2016 <- sd(market2016$return)
```

```{r}
# Beta calculations: correlation of sector with market * (sd of sector / sd of market)

beta_consumerGoods2000 <- correl_consumerGoods2000 * sd_consumerGoods2000 / sd_market2000
beta_consumerGoods2004 <- correl_consumerGoods2004 * sd_consumerGoods2004 / sd_market2004
beta_consumerGoods2008 <- correl_consumerGoods2008 * sd_consumerGoods2008 / sd_market2008
beta_consumerGoods2012 <- correl_consumerGoods2012 * sd_consumerGoods2012 / sd_market2012
beta_consumerGoods2016 <- correl_consumerGoods2016 * sd_consumerGoods2016 / sd_market2016

beta_realEstate2000 <- correl_realEstate2000 * sd_realEstate2000 / sd_market2000
beta_realEstate2004 <- correl_realEstate2004 * sd_realEstate2004 / sd_market2004
beta_realEstate2008 <- correl_realEstate2008 * sd_realEstate2008 / sd_market2008
beta_realEstate2012 <- correl_realEstate2012 * sd_realEstate2012 / sd_market2012
beta_realEstate2016 <- correl_realEstate2016 * sd_realEstate2016 / sd_market2016

beta_telecommunications2000 <- correl_telecommunications2000 * sd_telecommunications2000 / sd_market2000
beta_telecommunications2004 <- correl_telecommunications2004 * sd_telecommunications2004 / sd_market2004
beta_telecommunications2008 <- correl_telecommunications2008 * sd_telecommunications2008 / sd_market2008
beta_telecommunications2012 <- correl_telecommunications2012 * sd_telecommunications2012 / sd_market2012
beta_telecommunications2016 <- correl_telecommunications2016 * sd_telecommunications2016 / sd_market2016

beta_utilities2000 <- correl_utilities2000 * sd_utilities2000 / sd_market2000
beta_utilities2004 <- correl_utilities2004 * sd_utilities2004 / sd_market2004
beta_utilities2008 <- correl_utilities2008 * sd_utilities2008 / sd_market2008
beta_utilities2012 <- correl_utilities2012 * sd_utilities2012 / sd_market2012
beta_utilities2016 <- correl_utilities2016 * sd_utilities2016 / sd_market2016

beta_technology2000 <- correl_technology2000 * sd_technology2000 / sd_market2000
beta_technology2004 <- correl_technology2004 * sd_technology2004 / sd_market2004
beta_technology2008 <- correl_technology2008 * sd_technology2008 / sd_market2008
beta_technology2012 <- correl_technology2012 * sd_technology2012 / sd_market2012
beta_technology2016 <- correl_technology2016 * sd_technology2016 / sd_market2016

beta_industrial2000 <- correl_industrial2000 * sd_industrial2000 / sd_market2000
beta_industrial2004 <- correl_industrial2004 * sd_industrial2004 / sd_market2004
beta_industrial2008 <- correl_industrial2008 * sd_industrial2008 / sd_market2008
beta_industrial2012 <- correl_industrial2012 * sd_industrial2012 / sd_market2012
beta_industrial2016 <- correl_industrial2016 * sd_industrial2016 / sd_market2016

beta_financial2000 <- correl_financial2000 * sd_financial2000 / sd_market2000
beta_financial2004 <- correl_financial2004 * sd_financial2004 / sd_market2004
beta_financial2008 <- correl_financial2008 * sd_financial2008 / sd_market2008
beta_financial2012 <- correl_financial2012 * sd_financial2012 / sd_market2012
beta_financial2016 <- correl_financial2016 * sd_financial2016 / sd_market2016

beta_energy2000 <- correl_energy2000 * sd_energy2000 / sd_market2000
beta_energy2004 <- correl_energy2004 * sd_energy2004 / sd_market2004
beta_energy2008 <- correl_energy2008 * sd_energy2008 / sd_market2008
beta_energy2012 <- correl_energy2012 * sd_energy2012 / sd_market2012
beta_energy2016 <- correl_energy2016 * sd_energy2016 / sd_market2016

beta_consumerDiscretionary2000 <- correl_consumerDiscretionary2000 * sd_consumerDiscretionary2000 / sd_market2000
beta_consumerDiscretionary2004 <- correl_consumerDiscretionary2004 * sd_consumerDiscretionary2004 / sd_market2004
beta_consumerDiscretionary2008 <- correl_consumerDiscretionary2008 * sd_consumerDiscretionary2008 / sd_market2008
beta_consumerDiscretionary2012 <- correl_consumerDiscretionary2012 * sd_consumerDiscretionary2012 / sd_market2012
beta_consumerDiscretionary2016 <- correl_consumerDiscretionary2016 * sd_consumerDiscretionary2016 / sd_market2016

beta_healthCare2000 <- correl_healthCare2000 * sd_healthCare2000 / sd_market2000
beta_healthCare2004 <- correl_healthCare2004 * sd_healthCare2004 / sd_market2004
beta_healthCare2008 <- correl_healthCare2008 * sd_healthCare2008 / sd_market2008
beta_healthCare2012 <- correl_healthCare2012 * sd_healthCare2012 / sd_market2012
beta_healthCare2016 <- correl_healthCare2016 * sd_healthCare2016 / sd_market2016

beta_materials2000 <- correl_materials2000 * sd_materials2000 / sd_market2000
beta_materials2004 <- correl_materials2004 * sd_materials2004 / sd_market2004
beta_materials2008 <- correl_materials2008 * sd_materials2008 / sd_market2008
beta_materials2012 <- correl_materials2012 * sd_materials2012 / sd_market2012
beta_materials2016 <- correl_materials2016 * sd_materials2016 / sd_market2016
```

```{r}
#create vectors of each year, colors and dots and line
# Graph of all Betas as a function of time (elections)
#betas2000column <- c(beta_consumerGoods2000, beta_realEstate2000, beta_telecommunications2000, beta_utilities2000, #beta_technology2000, beta_industrial2000, beta_financial2000, beta_energy2000, beta_consumerDiscretionary2000, #beta_healthCare2000, beta_materials2000)

# Graph of Beta for each industry as a function of time (elections)
electionYears <- c("2000", "2004", "2008", "2012", "2016")


values_consumerGoodsBeta <- c(beta_consumerGoods2000, beta_consumerGoods2004, beta_consumerGoods2008, beta_consumerGoods2012, beta_consumerGoods2016)
betas_consumerGoods <- data.frame(electionYears, values_consumerGoodsBeta)
mid = 0
betasPlot_consumerGoods <- ggplot(data = betas_consumerGoods, aes(x = electionYears, y = values_consumerGoodsBeta, group = 1)) +
  geom_line(linetype = "dotted") + 
  geom_point(aes(colour = values_consumerGoodsBeta), size = 4) +
  scale_color_gradient2(midpoint = mid, low="red", mid = "green", high="red", breaks=c(-2.5,0,2.5), labels=c("Market Risk (-2.5)","No Market Risk (0)","Market Risk (2.5)"), limits=c(-2.5,2.5), name = "") +
  scale_y_continuous(limits=c(-2.5, 2.5)) +
  ylab("Beta"~(beta)~"\n") +
  xlab("Election Year") +
    labs(title = "Market risk of the consumer goods sector, as represented by Beta", subtitle = "(tracked 90 days before and 30 days after each election)", caption = "\n\n21st century comparison, excl. 2020") +
  theme(axis.title=element_text(size = 12, face = "bold")) +
  theme_solarized() +
  theme(legend.position="none")

values_realEstateBeta <- c(beta_realEstate2000, beta_realEstate2004, beta_realEstate2008, beta_realEstate2012, beta_realEstate2016)
betas_realEstate <- data.frame(electionYears, values_realEstateBeta)
mid = 0
betasPlot_realEstate <- ggplot(data = betas_realEstate, aes(x = electionYears, y = values_realEstateBeta, group = 1)) +
  geom_line(linetype = "dotted") + 
  geom_point(aes(colour = values_realEstateBeta), size = 4) +
  scale_color_gradient2(midpoint = mid, low="red", mid = "green", high="red", breaks=c(-2.5,0,2.5), labels=c("Market Risk (-2.5)","No Market Risk (0)","Market Risk (2.5)"), limits=c(-2.5,2.5), name = "") +
  scale_y_continuous(limits=c(-2.5, 2.5)) +
  ylab("Beta"~(beta)~"\n") +
  xlab("Election Year") +
    labs(title = "Market risk of the real estate sector, as represented by Beta", subtitle = "(tracked 90 days before and 30 days after each election)", caption = "\n\n21st century comparison, excl. 2020") +
  theme(axis.title=element_text(size = 12, face = "bold")) +
  theme_solarized() +
  theme(legend.position="none")

values_telecommunicationsBeta <- c(beta_telecommunications2000, beta_telecommunications2004, beta_telecommunications2008, beta_telecommunications2012, beta_telecommunications2016)
betas_telecommunications <- data.frame(electionYears, values_telecommunicationsBeta)
mid = 0
betasPlot_telecommunications <- ggplot(data = betas_telecommunications, aes(x = electionYears, y = values_telecommunicationsBeta, group = 1)) +
  geom_line(linetype = "dotted") + 
  geom_point(aes(colour = values_telecommunicationsBeta), size = 4) +
  scale_color_gradient2(midpoint = mid, low="red", mid = "green", high="red", breaks=c(-2.5,0,2.5), labels=c("Market Risk (-2.5)","No Market Risk (0)","Market Risk (2.5)"), limits=c(-2.5,2.5), name = "") +
  scale_y_continuous(limits=c(-2.5, 2.5)) +
  ylab("Beta"~(beta)~"\n") +
  xlab("Election Year") +
    labs(title = "Market risk of the telecommunications sector, as represented by Beta", subtitle = "(tracked 90 days before and 30 days after each election)", caption = "\n\n21st century comparison, excl. 2020") +
  theme(axis.title=element_text(size = 12, face = "bold")) +
  theme_solarized() +
  theme(legend.position="none")

values_utilitiesBeta <- c(beta_utilities2000, beta_utilities2004, beta_utilities2008, beta_utilities2012, beta_utilities2016)
betas_utilities <- data.frame(electionYears, values_utilitiesBeta)
mid = 0
betasPlot_utilities <- ggplot(data = betas_utilities, aes(x = electionYears, y = values_utilitiesBeta, group = 1)) +
  geom_line(linetype = "dotted") + 
  geom_point(aes(colour = values_utilitiesBeta), size = 4) +
  scale_color_gradient2(midpoint = mid, low="red", mid = "green", high="red", breaks=c(-2.5,0,2.5), labels=c("Market Risk (-2.5)","No Market Risk (0)","Market Risk (2.5)"), limits=c(-2.5,2.5), name = "") +
  scale_y_continuous(limits=c(-2.5, 2.5)) +
  ylab("Beta"~(beta)~"\n") +
  xlab("Election Year") +
    labs(title = "Market risk of the utilities sector, as represented by Beta", subtitle = "(tracked 90 days before and 30 days after each election)", caption = "\n\n21st century comparison, excl. 2020") +
  theme(axis.title=element_text(size = 12, face = "bold")) +
  theme_solarized() +
  theme(legend.position="none")

values_technologyBeta <- c(beta_technology2000, beta_technology2004, beta_technology2008, beta_technology2012, beta_technology2016)
betas_technology <- data.frame(electionYears, values_technologyBeta)
mid = 0
betasPlot_technology <- ggplot(data = betas_technology, aes(x = electionYears, y = values_technologyBeta, group = 1)) +
  geom_line(linetype = "dotted") + 
  geom_point(aes(colour = values_technologyBeta), size = 4) +
  scale_color_gradient2(midpoint = mid, low="red", mid = "green", high="red", breaks=c(-2.5,0,2.5), labels=c("Market Risk (-2.5)","No Market Risk (0)","Market Risk (2.5)"), limits=c(-2.5,2.5), name = "") +
  scale_y_continuous(limits=c(-2.5, 2.5)) +
  ylab("Beta"~(beta)~"\n") +
  xlab("Election Year") +
    labs(title = "Market risk of the technology sector, as represented by Beta", subtitle = "(tracked 90 days before and 30 days after each election)", caption = "\n\n21st century comparison, excl. 2020") +
  theme(axis.title=element_text(size = 12, face = "bold")) +
  theme_solarized() +
  theme(legend.position="none")

values_industrialBeta <- c(beta_industrial2000, beta_industrial2004, beta_industrial2008, beta_industrial2012, beta_industrial2016)
betas_industrial <- data.frame(electionYears, values_industrialBeta)
mid = 0
betasPlot_industrial <- ggplot(data = betas_industrial, aes(x = electionYears, y = values_industrialBeta, group = 1)) +
  geom_line(linetype = "dotted") + 
  geom_point(aes(colour = values_industrialBeta), size = 4) +
  scale_color_gradient2(midpoint = mid, low="red", mid = "green", high="red", breaks=c(-2.5,0,2.5), labels=c("Market Risk (-2.5)","No Market Risk (0)","Market Risk (2.5)"), limits=c(-2.5,2.5), name = "") +
  scale_y_continuous(limits=c(-2.5, 2.5)) +
  ylab("Beta"~(beta)~"\n") +
  xlab("Election Year") +
    labs(title = "Market risk of the industrial sector, as represented by Beta", subtitle = "(tracked 90 days before and 30 days after each election)", caption = "\n\n21st century comparison, excl. 2020") +
  theme(axis.title=element_text(size = 12, face = "bold")) +
  theme_solarized() +
  theme(legend.position="none")

values_financialBeta <- c(beta_financial2000, beta_financial2004, beta_financial2008, beta_financial2012, beta_financial2016)
betas_financial <- data.frame(electionYears, values_financialBeta)
mid = 0
betasPlot_financial <- ggplot(data = betas_financial, aes(x = electionYears, y = values_financialBeta, group = 1)) +
  geom_line(linetype = "dotted") + 
  geom_point(aes(colour = values_financialBeta), size = 4) +
  scale_color_gradient2(midpoint = mid, low="red", mid = "green", high="red", breaks=c(-2.5,0,2.5), labels=c("Market Risk (-2.5)","No Market Risk (0)","Market Risk (2.5)"), limits=c(-2.5,2.5), name = "") +
  scale_y_continuous(limits=c(-2.5, 2.5)) +
  ylab("Beta"~(beta)~"\n") +
  xlab("Election Year") +
    labs(title = "Market risk of the financial sector, as represented by Beta", subtitle = "(tracked 90 days before and 30 days after each election)", caption = "\n\n21st century comparison, excl. 2020") +
  theme(axis.title=element_text(size = 12, face = "bold")) +
  theme_solarized() +
  theme(legend.position="none")

values_energyBeta <- c(beta_energy2000, beta_energy2004, beta_energy2008, beta_energy2012, beta_energy2016)
betas_energy <- data.frame(electionYears, values_energyBeta)
mid = 0
betasPlot_energy <- ggplot(data = betas_energy, aes(x = electionYears, y = values_energyBeta, group = 1)) +
  geom_line(linetype = "dotted") + 
  geom_point(aes(colour = values_energyBeta), size = 4) +
  scale_color_gradient2(midpoint = mid, low="red", mid = "green", high="red", breaks=c(-2.5,0,2.5), labels=c("Market Risk (-2.5)","No Market Risk (0)","Market Risk (2.5)"), limits=c(-2.5,2.5), name = "") +
  scale_y_continuous(limits=c(-2.5, 2.5)) +
  ylab("Beta"~(beta)~"\n") +
  xlab("Election Year") +
    labs(title = "Market risk of the energy sector, as represented by Beta", subtitle = "(tracked 90 days before and 30 days after each election)", caption = "\n\n21st century comparison, excl. 2020") +
  theme(axis.title=element_text(size = 12, face = "bold")) +
  theme_solarized() +
  theme(legend.position="none")

values_consumerDiscretionaryBeta <- c(beta_consumerDiscretionary2000, beta_consumerDiscretionary2004, beta_consumerDiscretionary2008, beta_consumerDiscretionary2012, beta_consumerDiscretionary2016)
betas_consumerDiscretionary <- data.frame(electionYears, values_consumerDiscretionaryBeta)
mid = 0
betasPlot_consumerDiscretionary <- ggplot(data = betas_consumerDiscretionary, aes(x = electionYears, y = values_consumerDiscretionaryBeta, group = 1)) +
  geom_line(linetype = "dotted") + 
  geom_point(aes(colour = values_consumerDiscretionaryBeta), size = 4) +
  scale_color_gradient2(midpoint = mid, low="red", mid = "green", high="red", breaks=c(-2.5,0,2.5), labels=c("Market Risk (-2.5)","No Market Risk (0)","Market Risk (2.5)"), limits=c(-2.5,2.5), name = "") +
  scale_y_continuous(limits=c(-2.5, 2.5)) +
  ylab("Beta"~(beta)~"\n") +
  xlab("Election Year") +
    labs(title = "Market risk of the consumer discretionary sector, as represented by Beta", subtitle = "(tracked 90 days before and 30 days after each election)", caption = "\n\n21st century comparison, excl. 2020") +
  theme(axis.title=element_text(size = 12, face = "bold")) +
  theme_solarized() +
  theme(legend.position="none")

values_healthCareBeta <- c(beta_healthCare2000, beta_healthCare2004, beta_healthCare2008, beta_healthCare2012, beta_healthCare2016)
betas_healthCare <- data.frame(electionYears, values_healthCareBeta)
mid = 0
betasPlot_healthCare <- ggplot(data = betas_healthCare, aes(x = electionYears, y = values_healthCareBeta, group = 1)) +
  geom_line(linetype = "dotted") + 
  geom_point(aes(colour = values_healthCareBeta), size = 4) +
  scale_color_gradient2(midpoint = mid, low="red", mid = "green", high="red", breaks=c(-2.5,0,2.5), labels=c("Market Risk (-2.5)","No Market Risk (0)","Market Risk (2.5)"), limits=c(-2.5,2.5), name = "") +
  scale_y_continuous(limits=c(-2.5, 2.5)) +
  ylab("Beta"~(beta)~"\n") +
  xlab("Election Year") +
    labs(title = "Market risk of the health care sector, as represented by Beta", subtitle = "(tracked 90 days before and 30 days after each election)", caption = "\n\n21st century comparison, excl. 2020") +
  theme(axis.title=element_text(size = 12, face = "bold")) +
  theme_solarized() +
  theme(legend.position="none")

values_materialsBeta <- c(beta_materials2000, beta_materials2004, beta_materials2008, beta_materials2012, beta_materials2016)
betas_materials <- data.frame(electionYears, values_materialsBeta)
mid = 0
betasPlot_materials <- ggplot(data = betas_materials, aes(x = electionYears, y = values_materialsBeta, group = 1)) +
  geom_line(linetype = "dotted") + 
  geom_point(aes(colour = values_materialsBeta), size = 4) +
  scale_color_gradient2(midpoint = mid, low="red", mid = "green", high="red", breaks=c(-2.5,0,2.5), labels=c("Market Risk (-2.5)","No Market Risk (0)","Market Risk (2.5)"), limits=c(-2.5,2.5), name = "") +
  scale_y_continuous(limits=c(-2.5, 2.5)) +
  ylab("Beta"~(beta)~"\n") +
  xlab("Election Year") +
    labs(title = "Market risk of the materials sector, as represented by Beta", subtitle = "(tracked 90 days before and 30 days after each election)", caption = "\n\n21st century comparison, excl. 2020") +
  theme(axis.title=element_text(size = 12, face = "bold")) +
  theme_solarized() +
  theme(legend.position="none")
  
betasPlot_consumerGoods
betasPlot_realEstate
betasPlot_telecommunications
betasPlot_utilities
betasPlot_technology
betasPlot_industrial
betasPlot_financial
betasPlot_energy
betasPlot_consumerDiscretionary
betasPlot_healthCare
betasPlot_materials



#betasPlot_consumerGoods <- ggplot(data = betas_consumerGoods, aes(x = ))
#betas2000column
#betas2000 <- ggplot(data = betas2000column, aes(x = date, y = beta)) + geom_smooth(method=lm, color = "red")

```
```{r}
electionYears <- c("2000", "2004", "2008", "2012", "2016")


values_aggregateBeta <- c(values_consumerGoodsBeta, values_realEstateBeta, values_telecommunicationsBeta, values_utilitiesBeta, values_technologyBeta, values_industrialBeta, values_financialBeta, values_energyBeta, values_consumerDiscretionaryBeta, values_healthCareBeta, values_materialsBeta)

values_aggregateBeta

betas_aggregate <- data.frame(electionYears, values_aggregateBeta)
betas_aggregate
mid = 0
betasPlot_aggregate <- ggplot(data = betas_aggregate, aes(x = electionYears, y = values_aggregateBeta, group = 1)) +
  geom_point(aes(colour = values_aggregateBeta), size = 4) +
  geom_smooth(method = "lm") +
  scale_color_gradient2(midpoint = mid, low="red", mid = "green", high="red", breaks=c(-2.5,0,2.5), labels=c("Market Risk (-2.5)","No Market Risk (0)","Market Risk (2.5)"), limits=c(-2.5,2.5), name = "") +
  scale_y_continuous(limits=c(-2.5, 2.5)) +
  ylab("Beta"~(beta)~"\n") +
  xlab("Election Year") +
    labs(title = "Holistic view of the market risk of each sector, as represented by Beta", subtitle = "(tracked 90 days before and 30 days after each election)", caption = "\n\n21st century comparison, excl. 2020") +
  theme(axis.title=element_text(size = 12, face = "bold")) +
  theme_solarized() +
  theme(legend.position="none")

betasPlot_aggregate

```

```{r}
#Linear regression models
```

```{r}
winners <- c("1980R", "1984R", "1988R", "1992D", "1996D", "2000R", "2004R", "2008D", "2012D", "2016R" )
```

```{r}

```
## Including Plots

```{r pressure, echo=FALSE}
plot(pressure)
```